# Generated by Django 4.1.1 on 2023-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negaradunia_app", "0003_konservasi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="konservasi",
            name="nama_konservasi",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="konservasi",
            name="titik_koordinat",
            field=models.CharField(max_length=300),
        ),
    ]
